### PR TITLE
firstUI

### PR DESCRIPTION
**Pull request by JimmyWxzzz**
my current UI

### CODE REVIEW

**Comment by LeonYanc** [comment]
@zhangxyleon please review this PR

**Comment by JimmyWxzzz** [comment]
image

**Comment by JimmyWxzzz** [comment]
shortURL redirect to new tab

**Review by zhangxyleon — COMMENTED** [review]
could add more features compared to Bitly:
1. add copy button
2. show origin long Url in the list

**Comment by JimmyWxzzz** [comment]
> could add more features compared to Bitly:
> 
> 1. add copy button
> 2. show origin long Url in the list

the above recommendations has been added

**Review by LeonYanc — APPROVED** [review]

**Pull request merged**
